# Generated by Django 4.2.2 on 2023-06-18 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_cours', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Enseignants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_Enseignant', models.CharField(max_length=64)),
                ('mail_Enseignants', models.EmailField(max_length=254)),
                ('tel_Enseignants', models.CharField(max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_Licence', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_Master', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_Salle', models.CharField(max_length=20)),
                ('capacite_Salle', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Etudiants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_Etudiants', models.CharField(max_length=64)),
                ('mail_Etudiants', models.EmailField(max_length=254)),
                ('tel_Etudiants', models.CharField(max_length=18)),
                ('Filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.filiere')),
            ],
        ),
        migrations.CreateModel(
            name='Emplois',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(max_length=15)),
                ('heure_deb', models.CharField(max_length=15)),
                ('heure_fin', models.CharField(max_length=15)),
                ('Cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cours')),
                ('Enseignants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.enseignants')),
                ('Filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.filiere')),
                ('Licence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.licence')),
                ('Salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.salle')),
            ],
        ),
        migrations.AddField(
            model_name='cours',
            name='Filiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.filiere'),
        ),
        migrations.AddField(
            model_name='cours',
            name='Licence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.licence'),
        ),
    ]
