# Generated by Django 4.2.2 on 2023-06-20 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_classes', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_cours', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Enseignants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_Enseignant', models.CharField(max_length=64)),
                ('email_Enseignant', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_Salle', models.CharField(max_length=20)),
                ('capacite_Salle', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Semaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_semaine', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(max_length=15)),
                ('heure_deb', models.CharField(max_length=15)),
                ('heure_fin', models.CharField(max_length=15)),
                ('date', models.DateField(default=0.0005, verbose_name='date programme')),
                ('Cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cours')),
                ('Enseignants', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.enseignants')),
                ('Filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.filiere')),
                ('Salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.salle')),
                ('Semaine', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.semaine')),
            ],
        ),
    ]
