# Generated by Django 4.2.2 on 2023-06-21 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programme',
            name='date',
        ),
        migrations.AddField(
            model_name='programme',
            name='annee',
            field=models.CharField(default=1, max_length=17),
        ),
    ]
