# Generated by Django 4.2.2 on 2023-06-21 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Semaine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nemuro_semaine", models.IntegerField()),
                ("annee_scolaire", models.CharField(max_length=25)),
            ],
        ),
    ]
