# Generated by Django 4.2.2 on 2023-06-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_programme_date_programme_annee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='Cours',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='programme',
            name='Enseignants',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='programme',
            name='Filiere',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='programme',
            name='Salle',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='programme',
            name='Semaine',
            field=models.CharField(max_length=64),
        ),
    ]
