# Generated by Django 4.2.2 on 2023-06-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_enseignant"),
    ]

    operations = [
        migrations.AddField(
            model_name="semaine",
            name="date_debut",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="semaine",
            name="date_fin",
            field=models.DateField(null=True),
        ),
    ]
