# Generated by Django 4.2.2 on 2023-06-22 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_semaine_date_debut_semaine_date_fin"),
    ]

    operations = [
        migrations.CreateModel(
            name="Niveau",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=20)),
            ],
        ),
    ]
