# Generated by Django 4.2.2 on 2023-06-22 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_cours_niveau"),
    ]

    operations = [
        migrations.AddField(
            model_name="cours",
            name="filiere",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.filiere",
            ),
        ),
    ]
