# Generated by Django 4.2.2 on 2023-06-22 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_cours_filiere"),
    ]

    operations = [
        migrations.RenameField(
            model_name="programme",
            old_name="Salle",
            new_name="salle",
        ),
        migrations.RemoveField(
            model_name="programme",
            name="Cours",
        ),
        migrations.RemoveField(
            model_name="programme",
            name="Filiere",
        ),
        migrations.AddField(
            model_name="programme",
            name="niveau",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="home.niveau"
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="semaine",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.semaine",
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="cours",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="home.cours"
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="filiere",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.filiere",
            ),
        ),
    ]
