# Generated by Django 4.2.2 on 2023-06-22 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_rename_salle_programme_salle_remove_programme_cours_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programme",
            name="jour",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
