# Generated by Django 4.2.2 on 2023-06-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_alter_programme_jour"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programme",
            name="heure_deb",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="programme",
            name="heure_fin",
            field=models.IntegerField(),
        ),
    ]
