# Generated by Django 4.2.2 on 2023-06-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0014_alter_programme_heure_deb_alter_programme_heure_fin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programme",
            name="jour",
            field=models.CharField(default="Lundi", max_length=20),
        ),
    ]
