# Generated by Django 4.2.2 on 2023-06-22 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0015_alter_programme_jour"),
    ]

    operations = [
        migrations.AddField(
            model_name="programme",
            name="publich",
            field=models.BooleanField(default=False),
        ),
    ]
