# Generated by Django 4.2.2 on 2023-06-22 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0017_semaine_publich"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="programme",
            name="publich",
        ),
    ]
