# Generated by Django 4.2.2 on 2023-06-22 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0019_programme_enseignant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programme",
            name="enseignant",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.enseignant",
            ),
        ),
    ]
