# Generated by Django 4.2.2 on 2023-06-22 23:27

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.query


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0020_alter_programme_enseignant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programme",
            name="enseignant",
            field=models.ForeignKey(
                default=django.db.models.query.QuerySet.first,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.enseignant",
            ),
        ),
    ]
