# Generated by Django 4.2.2 on 2023-06-29 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_programme_filieres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Communique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('contenu', models.CharField(max_length=255)),
                ('date_commu', models.DateField(auto_now=True, null=True)),
            ],
        ),
    ]
