# Generated by Django 4.2.2 on 2023-07-03 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0025_cours_masse_horaire_alter_programme_heure_fin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programme",
            name="heure_fin",
            field=models.IntegerField(),
        ),
    ]
