# Generated by Django 4.2.2 on 2023-07-03 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0026_alter_programme_heure_fin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cours",
            name="masse_horaire",
            field=models.IntegerField(null=True),
        ),
    ]
